# Generated by Django 3.2.5 on 2021-07-16 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandspace_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='bandspace_app.user'),
        ),
    ]
