# Generated by Django 3.2.5 on 2021-07-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandspace_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('band_name', models.CharField(max_length=100)),
                ('photo', models.TextField()),
                ('about', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('music_url', models.TextField()),
            ],
        ),
    ]
