# Generated by Django 3.2.5 on 2021-07-14 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandspace_app', '0002_band'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='password',
        ),
        migrations.RemoveField(
            model_name='band',
            name='username',
        ),
        migrations.AddField(
            model_name='band',
            name='user',
            field=models.ForeignKey(default='Default Value', on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='bandspace_app.user'),
        ),
        migrations.CreateModel(
            name='UserFavBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandfavusers', to='bandspace_app.band')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfavbands', to='bandspace_app.user')),
            ],
        ),
    ]
