# Generated by Django 3.2.5 on 2021-07-16 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandspace_app', '0002_alter_band_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserFavBand',
        ),
    ]
