# Generated by Django 3.2.5 on 2021-07-14 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandspace_app', '0003_auto_20210714_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='bandspace_app.user'),
        ),
    ]
